### ISSUE TITLE
Incorrectly handling go 1.13 numerical literals with underscores

### ISSUE THREAD

**Issue by jakedt** [fixmie/feedback#12]
**Describe the bug**
I am using a go 1.13 literal (e.g. `1_000_000`) and fixme is saying that's wrong, and recommending that I rewrite that as `1`.

**To Reproduce**
Commit a change that uses a go 1.13 literal.

**Expected behavior**
It should not complain about this.

**Comment by fatih** [comment]
It seems like Fixmie is not updated yet for Go v1.13. Thanks @jakedt for the issue. I'll make sure to fix it soon.

**Comment by fatih** [comment]
@jakedt Fixmie is now updated. Please let me know if you still see an issue. Thank you.
