### ISSUE TITLE
Do not suggest bad doc comments

### ISSUE THREAD

**Issue by AlekSi** [fixmie/feedback#2]
I don't want fixmie to suggest bad doc comments.

![image](https://user-images.githubusercontent.com/11512/49086614-03d9ee00-f266-11e8-9b3f-feadde12699c.png)

The lack of a proper doc comment is the real problem. Proposed fix to make golint happy will make me very unhappy. 😞

**Comment by fatih** [comment]
Hi @AlekSi 

Thanks for the feedback. There are two things here.

* First, in the future you'll be able to disable certain "comments" fixers. Some people prefer seeing them, as a reminder that they need to add something, doesn't have to be this commen. So you'll be able to disable them 
* Second, in the future, you'll able to comment on this fix with your own "comment", and fixmie will update the suggestion with the suggestion you provided. With that, you'll be able to add quick suggestions without editing any file locally.

Hope this helps and thanks again for your suggestion.

**Comment by AlekSi** [comment]
If you plan to implement the first feature well before the second one, may I suggest to add only comments, but not suggestions? Just like https://golangci.com is doing. In the current form, it is too easy to make a fix that will make golint happy, fixmie happy, PR status green, but the code will become worse.

The second feature sounds wonderful!

**Comment by fatih** [comment]
Thanks. Fixmie is based on suggestions, it's the same as comments, but you don't have to apply the suggestion yourself. Maybe in the future we can add a toggle to disable suggestions, but that's the core feature of Fixmie, it fixes stuff for you :) (whether it's useful or not will be improved with time of course)

**Comment by narqo** [comment]
I tend to agree with @AlekSi, code comments are great when they have been written to help those who read the code, not to shut your linter or CI.

The list of future improvements you'd posted looks wonderful. Maybe there's a possibility to disable the feature until it's fully ready?

Alternatively, the suggestion might have a note, which implies or even suggests editing fixmie's comment, adding a proper code comment, instead of `...` part. This might sound like an obvious thing, but it's not.

**Comment by fatih** [comment]
Hi,

There is now support for `.fixmie.yml` file. This allows you to change certain aspects of .fixmie.com. For example you can now disable the `comments` mode via by adding the following `.fixmie.yml` file:

```yaml
go:
  comments:
    disabled: true
```

For more information on the various options in the file, please check out the current documentation: https://github.com/fixmie/docs
