### ISSUE TITLE
Ignore certain folders with generated code

### ISSUE THREAD

**Issue by metalmatze** [fixmie/feedback#3]
**Is your feature request related to a problem? Please describe.**
I've just enabled fixmie with a repository that has a few folders that contain generated code (swagger, gRPC). I would like to be able to simply exclude these.

**Describe the solution you'd like**
I would like to have a configuration file, maybe similar to what a `.gitignore` does for fixmie.

**Describe alternatives you've considered**
Not sure what an alternative would be, probably deactivating fixmie for the repository in the meantime :confused: 

Thanks for fixmie!

**Comment by fatih** [comment]
Hi @metalmatze 

We're actually ignoring these files. This is the list of things that fixmie will ignore:

```
func shouldIgnore(fname string) bool {
	return strings.Contains(fname, "vendor/") ||
		strings.HasSuffix(fname, ".gen.go") ||
		strings.HasSuffix(fname, ".pb.go")
}
```

Can you provide an example where it has failed for you?

**Comment by metalmatze** [comment]
These seem like really good defaults! However, when generating code that doesn't match this criteria, it will obviously comment, like in https://github.com/gitpods/gitpods/pull/22#pullrequestreview-189628251.
The problem here is, that the files aren't in `vendor/` and don't have the suffixes you want to match, as they are simple Go files in `internal/api/v1`.

**Comment by fatih** [comment]
@metalmatze how do you think can we identify that these are generatd files? Does it have a string like `"DO NOT EDIT"` or `generated`  inside the files? `.gitignore` like approach is fine, but I have to think how to implement it in a proper way. 

There will be a `.fixmie.yaml` file which you can use to disable certain fixers (such as comments). I think we can use the same file  for setting some configurations.

**Comment by metalmatze** [comment]
Yep. I think those by swagger generated Go files have `// Code generated by go-swagger; DO NOT EDIT.` as their first line. So this should be an option to simple ignore these files.
A simple list of folders to exclude in `.fixmie.yml` also sounds really good. :+1:

**Comment by fatih** [comment]
Thanks @metalmatze for the information. The issue with skipping those files is, I have to download them first so I know that I can skip it. So it consumes additional API calls and bandwidth on my side, but I'm already downloading them nevertheless, so it shouldn't be a problem. Let's keep this issue open, I'll close this once I have something implemented that solves our issue 👍

**Comment by fatih** [comment]
This is now fixed in production. Thanks for the feedback. From now on, any generated files will be skipped and not checked.

**Comment by metalmatze** [comment]
Wow. Awesome. That was quick! 🚀
Going to enable fixmie tomorrow again. 
Thank you!
