### ISSUE TITLE
Fixmie app name is wrong in GitHub PR checks

### ISSUE THREAD

**Issue by mattkelly** [fixmie/feedback#4]
**Describe the bug**

`code-analysis/fixme` below should be `code-analysis/fixmie`:

![image](https://user-images.githubusercontent.com/248713/51077385-30aa5f00-1674-11e9-826b-ecab6749e83d.png)

**To Reproduce**
Here's an example PR, though it may be merged soon: https://github.com/containership/csctl/pull/78

**Expected behavior**
`fixmie` is spelled properly.

**Screenshots**
See above.

**Additional context**

I also noticed that `Fixmie` is spelled `Fixme` under the "How much does it cost?" section here: https://fixmie.com/.

Thanks for the great project!

**Comment by fatih** [comment]
Thank you so much @mattkelly I just fixed them, let me know if you see any other typos.
