### ISSUE TITLE
Should ignore folder starting with _

### ISSUE THREAD

**Issue by markbates** [fixmie/feedback#5]
Go ignores folders that begin with `_`, so for example Go will ignore `_fixtures/foo.go`. Fixmie should also ignore those same folders.

**Comment by fatih** [comment]
It seems like files starting with underscore are excluded, but not folders. Thanks for the feedback, this makes sense. I'll try to add this soon and close this issue once it's deployed to production.

**Comment by fatih** [comment]
Hi Mark,

Thanks for the feedback. We ignore now any file or folder that starts with `_` for the `go` fixer. We also support now the new `.fixmie.yml` file that allows you to add custom folders/files to ignore or change the way fixmie works. Checkout the docs for more information: https://github.com/fixmie/docs

As always, thanks for the feedback and please don't hesitate to share any issues or feedbacks :)

**Comment by markbates** [comment]
Thanks Fatih. Now, instead of fixing my bugs, go spend time with that beautiful little girl of yours. :)

**Comment by fatih** [comment]
Haha thanks Mark! She was sleeping and I was working on this occasionally on a branch, so I thought I finalize it. See you!
