### ISSUE TITLE
Highlighting code blocks

### ISSUE THREAD

**Issue by gokaygurcan** [fixmie/feedback#6]
**Is your feature request related to a problem? Please describe.**
Hi,
I was checking https://fixmie.com/ and the first screenshot (you can see it below) was a bit.. obscure. Having normal text and code recommendations in the same format makes things a bit harder to understand.

**Describe the solution you'd like**
Instead of replying 

should replace errors.New(fmt.Sprintf("something %d", x)) with fmt.Errorf("something %d", x)

maybe it'd be better to reply like

should replace `errors.New(fmt.Sprintf("something %d", x))` with `fmt.Errorf("something %d", x)`

**Describe alternatives you've considered**
As an alternative, it might even highlight correctly but replying like:

should replace 
```go
errors.New(fmt.Sprintf("something %d", x))
``` 
with 
```
fmt.Errorf("something %d", x)
```

**Additional context**
Here we go, that screenshot from the webpage: 
![image](https://user-images.githubusercontent.com/1509413/51189566-9a2ea580-18e0-11e9-8b39-9b52fe4606c4.png)

**Comment by gokaygurcan** [comment]
Well, I must say, I'm not using the tool so IDK how that "suggested change" block looks like. If it's working fine, then I'd suggest to change that text completely. No need to mention the same changes in two places I guess.

**Comment by fatih** [comment]
Hi @gokaygurcan 

Thanks for the suggestion. I'll have to look how to format it, should be an easy task.

> No need to mention the same changes in two places I guess.

This is just one example, sometimes the text describes why the change was made. It depends on the fixer itself and every suggestion has a text, it needs to be something. But these are little improvements we can make over the course of developing Fixmie. Thanks again, I'll close this once I have some time to improve them :)

**Comment by gokaygurcan** [comment]
Thanks! Looks like a nice tool, I wish I was writing some Go ^_^

**Comment by fatih** [comment]
This is partly fixed now with the following change. 

<img width="671" alt="screen shot 2019-01-26 at 03 15 35" src="https://user-images.githubusercontent.com/438920/51779489-af91a400-2118-11e9-93c8-a9d0670a431d.png">

Multi line message is not supported yet so I'll take a look at them in near future. It's not a high priority for now. Thanks for the feedback again. It's pushed to product.

**Comment by gokaygurcan** [comment]
Perfect! It seems a lot more descriptive and clear now. Thanks again and good luck!
