### ISSUE TITLE
unnamed return triggers "replaces predefined value"

### ISSUE THREAD

**Issue by bkcsoft** [fixmie/feedback#7]
**Describe the bug**
when I have `func foo() error {`, fixmie wants me to replace `error` with `errorVal` (which is not defined) for some reason.

**To Reproduce**
https://github.com/sourcepods/sourcepods/pull/52#discussion_r251217488

**Expected behavior**
I expect it not to suggest such an edit :thinking: 

**Screenshots**
![https://i.imgur.com/2qT1bTf.png](https://i.imgur.com/2qT1bTf.png)

**Additional context**

**Comment by fatih** [comment]
Thanks @bkcsoft. This mode is new and this definetely a bug. Bug reports like this is very important so I can catch the edge cases. Sorry for the inconvenient comments, I’ll make sure to check it out and fix it. Please keep sending bug reports if you see any.

**Comment by fatih** [comment]
This is now fixed and pushed to production. If you force push to the PR or add a new commit it'll re-sync. Thanks again for the bug report.
