### ISSUE TITLE
named function parameters sharing a type style nit 

### ISSUE THREAD

**Issue by adamdecaf** [fixmie/feedback#8]
**Describe the bug**
On https://github.com/moov-io/base/pull/40 the fixmie bot reported: 

> two or more consecutive named function parameters share a type, you can omit the type from all but the last

I get that it saves a few characters, but that style preference is a bit "too picky" for my taste. Do we need the bot to report on that?

**Comment by fatih** [comment]
All features are subjective and unfortunately we can't please everyone :) I like it and I wouldn't let this get through a review (unless there is a compelling reason) 

However some people prefer the way around. You can disable it if you don't like it, please checkout the docs: https://github.com/fixmie/docs#go-1

Thanks!

**Comment by adamdecaf** [comment]
That's fair, thanks!
