### ISSUE TITLE
Getting "named function parameters sharing a type" on return types

### ISSUE THREAD

**Issue by hairyhenderson** [fixmie/feedback#9]
**Describe the bug**

Here: https://github.com/hairyhenderson/gomplate/pull/516#discussion_r266222811

I'm getting this message:

```
two or more consecutive named function parameters share a type, you can omit the type from all but the last
```

The suggested patch is:

```patch
- func toCodePoints(l, u string) (rune, rune, error) {
+ func toCodePoints(l, u string) (rune, error) {
```

This suggestion would break the code!

**To Reproduce**

Here: https://github.com/hairyhenderson/gomplate/pull/516#discussion_r266222811

**Expected behavior**

I expect Fixmie to not suggest anything on this line at all 😉

**Screenshots**

Not sure if the linked comment will persist - in case it doesn't:

<img width="786" alt="Screen Shot 2019-03-16 at 23 32 15" src="https://user-images.githubusercontent.com/2037086/54484805-bf3d8700-4843-11e9-8e8f-de635ca1f0c8.png">

**Comment by fatih** [comment]
Thanks @hairyhenderson. Yeap this is definitely a bug. I'll close this issue once it's fixed. Thanks for reporting!

**Comment by fatih** [comment]
Thanks again for the feedback. This is now fixed in production. Please let me know if you still see anything wrong. Thanks!

**Comment by hairyhenderson** [comment]
Thanks @fatih!
